#include "TApplication.h"
#include "TRootCanvas.h"
#include <boost/chrono.hpp>

//#include "/home/stm_mu2e/claudiaa/STMDAQ-TestBeam/Claudia/Bremsstrahlung/MinuitFITTER/MinuitFitter.h"
#include "/work/cgarcia/STMDAQ-TestBeam/Claudia/Bremsstrahlung/MinuitFITTER/MinuitFitter.h"

//1- This code reads the data (hSTM1) in the root file generated by Fitter.cc from several root files 
//2- Adds them together
//3- and fit it with minuit to get one point with good statistics

void AddData_LaBrStatistics(int argc, char *argv[], std::string path_roots, int FitOption, double seed)
{

#if defined(USE_GRAPHICS)
  TApplication app("app", &argc, argv);
#endif

  bool save_tologfile = true; 
  bool store_dataROOT = true;

  std::cout<<"Seed: "<<seed<<std::endl;

  gROOT->SetStyle("ATLAS");
  gStyle->SetOptStat(1111);
  TCanvas* c = new TCanvas();



  //Generate one root file with the combined data     
  std::vector<double> TrueSignal_fullfit, RecoSignal_fullfit;
  TFile*output;
  std::string rootfile = path_roots.substr(path_roots.find("/data1/"), 39)+"CombinedDataFit.root";

  output = new TFile(rootfile.c_str(),"recreate");

  std::string Label_log = path_roots.substr(path_roots.find("/data1/"), 39)+"Accuracy_LaBr_FullDataHistogram.log";
  char* char_Label_log = const_cast<char*>(Label_log.c_str());
  std::cout<<"Generated log file: "<<Label_log<<std::endl;
  if( save_tologfile == true ){
    gSystem->RedirectOutput(char_Label_log);
  }

  boost::chrono::high_resolution_clock::time_point t1 ;
  boost::chrono::high_resolution_clock::time_point t2 ;

  //***********READ DATA***********//

  string root_path;
  std::vector<string> rootpath_name;

  fstream readfile_txt;
  readfile_txt.open( path_roots, ios::in );

  //Reading root files in the txt file
  while(1){

    readfile_txt >> root_path;
    rootpath_name.push_back(root_path);
    if(readfile_txt.eof()) break;

  }

  unsigned long int num_files = rootpath_name.size() -1 ;

  std::cout<<"Number of files read: "<<num_files<<std::endl;

  double simtime_per_root = 1000; //s 
  double TimeSim = num_files * simtime_per_root;

  std::cout<<"Simulated data time: "<<num_files<<"x"<<simtime_per_root<<" = "<<TimeSim<<"s"<<std::endl;

  //Initialise Minuit Class  
  MinuitFitter *fitter = new MinuitFitter(FitOption, seed);

  //Return number of fit parameters NP
  int NP = fitter->return_NP();
  std::cout<<"Number of fit parameters, NP: "<<NP<<std::endl;
  double frange[2], fit_range[2];
  frange[0] = fitter->return_frange_min();
  frange[1] = fitter->return_frange_max();
  fit_range[0] = frange[0];
  fit_range[1] = frange[1];

  TH1D *hSTM;
  TH1D *hSTM_FullData;
  std::vector<double> *TrueSignal=0, *RecoSignal=0;
  double *best_fitpar = new double[NP];
  double true_peaks = 0;

  for ( unsigned long int i = 0; i < num_files; i++ ) {
    std::cout<<"Root file "<<i<<" : "<<rootpath_name.at(i)<<std::endl;
    TFile *infile = new TFile(rootpath_name.at(i).c_str());
    
    //Read the data
    std::string str_hSTM = "hSTM1";
    char* char_hSTM = const_cast<char*>(str_hSTM.c_str());
    hSTM = (TH1D*)infile->Get(char_hSTM);
    double binning = hSTM->GetBinWidth(1);
    unsigned long int Nbins = (frange[1]-frange[0])/binning;


    TTree *treeread=(TTree*)infile->Get("Signaltree");
    treeread->SetBranchAddress("TrueSignal",&TrueSignal);
    treeread->SetBranchAddress("RecoSignal",&RecoSignal);

    treeread->GetEntry(0);

    true_peaks = true_peaks+TrueSignal->at(0);

    std::cout<<"Reading Data generated... with binning: "<<binning<<" Nbins: "<<Nbins<<std::endl;

    //TMatrixD *Covmatrix = (TMatrixD*)infile->Get("Covmatrix");

    if( i==0 ){
      hSTM_FullData = new TH1D("hSTM_FullData", "", Nbins, frange[0], frange[1]);
    }

    //If we're in first root file, store best fit parameters to use as inputs for fit
    if( i==2 ){
      std::cout<<"Using best fit parameters from file: "<<i<<std::endl;
      TMatrixD *BestFitPars = (TMatrixD*)infile->Get("BestFitPars1");
      TMatrixD _BestFitPars(1,NP,BestFitPars->GetMatrixArray(),"");
      std::cout<<"Best fit parameters for first root file..."<<std::endl;
      _BestFitPars.Print();
      for( int k = 0 ; k < NP ; k++ ){
	best_fitpar[k] = _BestFitPars[0][k];
      }
    }

    hSTM_FullData->Add(hSTM);
    hSTM->Reset();
  }

  //hSTM_FullData->Draw();

  //***********START CODE***********//
  
  unsigned long int nbins = fitter->return_nbins();

  std::cout<<"Number of bins from fitter: "<<nbins<<std::endl;

  //Get histogram bin content and errors in fitrange to form the data
  fitter->Histo_Data(fit_range, hSTM_FullData); //Get nbins_fit, _binning, bincontent, bincontent_error, bincenter

  //Return nbins for the fit
  unsigned long int nbins_fit = fitter->return_nbinsfit();
  double bin_width = hSTM_FullData->GetBinWidth(0);
  std::cout<<"hSTM full data bin width: "<<bin_width<<std::endl;
  double* p_minuit;
  double* perr_minuit;
  double min_fcn, error_def;
  TMatrixD* Covmatrix_fulldata;

  TF1* ffit;

  double reco_peaks;
  double reco_sigma;
  char* char_Covmatrix;
  char* char_BestFitPars;

  std::cout<<"Nbins to do the fit: "<<nbins_fit<<std::endl;

  //Initialise parameters value to do the fit
  double par_fit [NP];

  //This is for using binned loglike or binned chi2
  //Signal
  par_fit [0] = best_fitpar[0] * num_files;
  par_fit [1] = best_fitpar[1] ;
  par_fit [2] = best_fitpar[2] ;
  //Background
  par_fit [3] = best_fitpar[3] * num_files;
  par_fit [4] = best_fitpar[4] ;
  par_fit [5] = best_fitpar[5] ;
  par_fit [6] = best_fitpar[6] * num_files;

  //Initialise S+B function
  std::string  genfunc_name = "fgenSB";
  char* char_genfunc_name = const_cast<char*>(genfunc_name.c_str());
  fitter->Init_SBfunc(char_genfunc_name, fit_range);
  fitter->SetPar_SBfunc(par_fit);

  //Fit with Minuit
  fitter->fit(par_fit, NP);

  //Get Minuit fit parameters
  p_minuit = new double[NP];
  perr_minuit = new double[NP];

  p_minuit = fitter->return_p_minuit();
  perr_minuit = fitter->return_perr_minuit();
  min_fcn = fitter->return_amin();
  error_def = fitter->return_errdef();
  Covmatrix_fulldata = fitter->return_Covmatrix();

  //Draw Minuit fit
  std::string  fitfunc_name = "ffit";
  char* char_fitfunc_name = const_cast<char*>(fitfunc_name.c_str());
  std::cout<<"Minuit parameters: "<<std::endl;
  std::cout<<"min FCN: "<<min_fcn<<" error definition: "<<error_def<<std::endl;

  double par_minuit [NP];
  for(int i = 0 ; i < NP; i++) {
    std::cout<<p_minuit[i]<<" +- "<<perr_minuit[i]<<std::endl;
    par_minuit [i] = p_minuit[i];
  }

  //Recovered number of peaks in signal
  std::cout<<"True peaks from combined data: "<< true_peaks <<std::endl;
  reco_peaks = par_minuit [0] / bin_width;
  std::cout<<"Peaks recovered from Binned fit: "<< reco_peaks <<std::endl;
  TMatrixD _Covmatrix_fulldata(7,7,Covmatrix_fulldata->GetMatrixArray(),"");
  reco_sigma = sqrt(_Covmatrix_fulldata[0][0]) / bin_width;
  std::cout<<"Covariance matrix for combined data: " <<std::endl;
  _Covmatrix_fulldata.Print();
  std::string str_Covmatrix = "Covmatrix1";
  char_Covmatrix = const_cast<char*>(str_Covmatrix.c_str());

  std::string str_BestFitPars = "BestFitPars1";
  char_BestFitPars = const_cast<char*>(str_BestFitPars.c_str());
  TMatrixD _BestFitPars_fulldata(NP,1);
  for( int j = 0; j < NP; j++) {
    _BestFitPars_fulldata[j][0] = par_minuit[j];
  }
  TMatrixD* BestFitPars_fulldata = new TMatrixD(NP,1,_BestFitPars_fulldata.GetMatrixArray(),"");
  std::cout<<"Best fit parameters for combined data: " <<std::endl;
  _BestFitPars_fulldata.Print();


  if(store_dataROOT==true) {

    output->WriteObject(hSTM_FullData, "hSTM1");
    output->WriteObject(Covmatrix_fulldata, char_Covmatrix);
    output->WriteObject(BestFitPars_fulldata, char_BestFitPars);
 
    TTree* Signaltree = new TTree("Signaltree", "Signaltree");
    Signaltree->Branch("TrueSignal", &TrueSignal_fullfit);
    Signaltree->Branch("RecoSignal", &RecoSignal_fullfit);
    TrueSignal_fullfit.push_back(true_peaks);
    RecoSignal_fullfit.push_back(reco_peaks);

    Signaltree->Fill();

    std::cout<<"Filling tree... "<<TrueSignal_fullfit.at(0)<<" "<<RecoSignal_fullfit.at(0)<<std::endl;
    output->WriteObject(Signaltree, "Signaltree");
   
  }



  std::cout<<"Sigma Signal: sqrt(cov matrix element)/bin width: "<<sqrt(_Covmatrix_fulldata[0][0])<<"/"<<bin_width<<"="<<reco_sigma<<std::endl;
  std::cout<<"Reco signal: "<<reco_peaks<<std::endl;
  double accuracy = reco_sigma / reco_peaks;
  std::cout<<"Accuracy (sigma/signal): "<< accuracy <<std::endl;


  double accuracy_error;
  double sigma_sigmaS = 1./sqrt(2);
  double factor1 = sigma_sigmaS / reco_sigma;
  double factor2 = reco_sigma / reco_peaks;
  double factor_acc = sqrt((factor1 * factor1) + (factor2*factor2));
  accuracy_error = accuracy*factor_acc ;
  std::cout<<"Accuracy error: "<< accuracy_error <<std::endl;

  double time_acc = (accuracy/0.1)*(accuracy/0.1)*TimeSim;
  double time_acc_error = 2*accuracy*TimeSim*accuracy_error/(0.1*0.1);
  std::cout<<"Time for accuracy=0.1 = "<<time_acc<<" +- "<<time_acc_error<<" s"<<std::endl;


  fitter->Init_SBfunc(char_fitfunc_name, fit_range);
  fitter->SetPar_SBfunc(par_minuit);
  ffit = fitter->return_fSB();

  bool drawplot = true;

  if( drawplot==true ) {

    double ymax;
    ymax = hSTM_FullData->GetMaximum();
    double plot_y_range[2]={0,ymax};
    double plot_x_range[2]={0.04,2};
    TGraph *graph1 = new TGraph (2, plot_x_range, plot_y_range);
    graph1->GetXaxis()->SetRangeUser(plot_x_range[0], plot_x_range[1]);
    graph1->GetYaxis()->SetRangeUser(plot_y_range[0], plot_y_range[1]);
    graph1->GetXaxis()->SetTitle("E_{#gamma} (STM) [MeV]");
    string yaxis_str;
    char*  yaxis_char;
    yaxis_str = "Counts / run time "+std::to_string(int(TimeSim))+" s";
    yaxis_char = const_cast<char*>(yaxis_str.c_str());
    graph1->GetYaxis()->SetTitle(yaxis_char);
    graph1->SetTitle("");
    graph1->SetMarkerStyle(1);
    graph1->Draw("ap");

    hSTM_FullData->SetFillColor(kOrange-3);
    hSTM_FullData->SetLineColor(kOrange-3);
    hSTM_FullData->SetFillStyle(3001);
    hSTM_FullData->Draw("same");

    ffit->SetLineColor(kBlack);
    ffit->SetLineStyle(2);
    ffit->Draw("same");

  }

 

  std::string Label_png = path_roots.substr(path_roots.find("/data1/"), 39)+"Accuracy_LaBr_FullDataHistogram.png";
  char* char_Label_png = const_cast<char*>(Label_png.c_str());
  c->Print(char_Label_png);

  output->Close();

  std::cout<<"Generated png file: "<<Label_png<<std::endl;
  std::cout<<"Generated root file: "<<rootfile<<std::endl;

  t2 = boost::chrono::high_resolution_clock::now();
    
  std::cout<< "Computing time: " << boost::chrono::duration_cast<boost::chrono::milliseconds>(t2-t1) << std::endl;

 
  //***********END CODE***********//

#if defined(USE_GRAPHICS)
  TRootCanvas *rc = (TRootCanvas *)c->GetCanvasImp();
  rc->Connect("CloseWindow()", "TApplication", gApplication, "Terminate()");
  app.Run();
#endif
}




int main(int argc, char *argv[]) {

  std::string path_roots = argv[1];
  int FitOption = std::atoi(argv[2]);
  double seed = std::stod(argv[3]);

  AddData_LaBrStatistics(argc, argv, path_roots, FitOption, seed);

  return 0;
}
