#!/bin/bash

/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "01" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_01kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "05" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_05kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "10" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_10kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "20" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_20kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "30" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_30kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "40" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_40kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "50" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_50kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "80" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_80kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "100" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_100kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "120" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_120kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "150" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_150kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "180" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_180kHzbyparts.txt
/work/cgarcia/STMDAQ-TestBeam/build/bin/GenData.exe "200" 2370 0.32 /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS > /work/cgarcia/DATA/Claudia/GenData/GaussianNoise_SimPoisson/Height1185ADCCounts/sigmaNoise0.32mVBYPARTS/GendataNoise_200kHzbyparts.txt
