// Thread functions code                                                       
#include "thread_funcs.hh"

std::vector<int16_t> dummy_data;
int len = (60*1024*1024)/2;


// Constructor
ThreadFuncs::ThreadFuncs() : threadDone(threadNum) {

  // Initialise thread completion flags
  for (auto& flag : threadDone) {
    // Initialise as false
    flag.store(false);                                                    
  }

}

// Pin thread to specific CPU core
void ThreadFuncs::pin_thread_to_core(size_t core_id) {

  // Define CPU set
  cpu_set_t cpuset;
  // Clear CPU set
  CPU_ZERO(&cpuset);
  // Add specified core to set 
  CPU_SET(core_id, &cpuset);
  // Set thread affinity
  pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuset);
  
}

// Starter thread to fill first buffer
void ThreadFuncs::starterThread(RingBuffer<DataStruct>& outputQueue,
				 BufferPool& pool,
				 size_t core_id) {

  // Bind thread to specific core
  pin_thread_to_core(core_id);

  dummy_data.resize(len);
  for (size_t i = 0; i < len; ++i) {
    dummy_data[i] = (10-i);
  }

  // Continue until total bytes processed reaches target
  while (globalTotalBytes < targetTotalBytes) {

    // Acquire a buffer from the pool
    auto buffer = pool.acquire();
    // If no buffer available...
    if (!buffer) { // Wait for an available buffer
      std::this_thread::yield();
      continue;
    }
    
    // Simulate variable buffer size
    //    buffer->size = (rand() % (60 * 1024 * 1024 / sizeof(int16_t))) + 1000;
    buffer->size = len;//dummy_data.size();
    // Fill buffer with simulated data
    //    memset(buffer->data.data(), rand() % 100, buffer->size * sizeof(int16_t));
    buffer->data = dummy_data;
    // Add metadata
    strncpy(buffer->metadata, "Generated by kernelBufferWorker", sizeof(buffer->metadata));

    // Calculate bytes generated
    uint64_t bytesGenerated = buffer->size * sizeof(int16_t);
    // Update global total bytes processed
    globalTotalBytes += bytesGenerated;

    // Push buffer to output queue
    outputQueue.push(buffer);
    
  }

  // Signal the first worker thread
  threadDone[0].store(true);

}


// General worker function for processing stages
void ThreadFuncs::workerThread(RingBuffer<DataStruct>& inputQueue,
			       RingBuffer<DataStruct>& outputQueue,
			       BufferPool& pool,
			       const char* stage,
			       std::atomic<uint64_t>& totalBytesProcessed,
			       size_t core_id,
			       std::function<void(std::shared_ptr<DataStruct>&)> operation,
			       size_t threadIndex) {


  // Bind thread to specific core
  pin_thread_to_core(core_id);

  bool first = true;
  
  // Start timing
  auto start_time = std::chrono::high_resolution_clock::now();
  
  // Continue until first thread is done, input queue is empty
  // and previous thread is done
  while (!threadDone[0].load() || !inputQueue.is_empty() || !threadDone[threadIndex - 1].load()) {

    // Retrieve a buffer from the input queue
    auto buffer = inputQueue.pop();

    // If buffer is valid
    if (buffer) {

      // Restart timer
      if (first){
	start_time = std::chrono::high_resolution_clock::now(); 
	first = false;
      }            

      // Perform the operation on the buffer
      operation(buffer); 

      // Append stage-specific metadata
      strncat(buffer->metadata, stage, sizeof(buffer->metadata) - strlen(buffer->metadata) - 1);

      // Calculate bytes processed 
      uint64_t bytesProcessed = buffer->size * sizeof(int16_t);
      // Update total bytes processed 
      totalBytesProcessed += bytesProcessed;

      // Push the processed buffer to the next stage
      outputQueue.push(buffer);
      
    }
    
  }

  // End timing
  auto end_time = std::chrono::high_resolution_clock::now();

  // Signal completion to the next thread
  threadDone[threadIndex].store(true);

  // Calculate elapsed time 
  std::chrono::duration<double> elapsed = end_time - start_time;
  // Convert bytes to Gbits
  double gbytes = totalBytesProcessed.load() / 1e9;
  double gbits = gbytes * 8.0; // Convert to Gbits
  // Print processing speed
  std::cout << "[" << stage << "] Processed "
	    << std::fixed << std::setprecision(2)
	    << (gbytes) << " Gbytes at\n"
      	    << std::fixed << std::setprecision(2)
	    << (gbits / elapsed.count()) << " Gbit/s\n";

}


// Ending thread to ensure the final buffer is emptied
void ThreadFuncs::endingThread(RingBuffer<DataStruct>& inputQueue,
			       BufferPool& pool,
			       size_t core_id,
			       size_t threadIndex) {

  // Bind thread to specific core
  pin_thread_to_core(core_id);

  bool success = true;
  
  // Continue until first thread is done, input queue is empty
  // and previous thread is done
  while (!threadDone[0].load() || !inputQueue.is_empty() || !threadDone[threadIndex - 1].load()) {

    // Retrieve a buffer from the input queue
    auto buffer = inputQueue.pop();
    // Retry if buffer is invalid
    if (!buffer) continue;
    for (size_t i = 0; i < buffer->size; ++i) {
      int16_t test = dummy_data[i]+3;
      if (buffer->data[i] != test){
    	std::cout << "BUFFER 1 ERROR: " << buffer->data[i] << " != " << test << std::endl;
	exit(0);
      }
      int16_t test2 = (test)*2;
      if (buffer->data2[i] != test2){
    	std::cout << "BUFFER 2 ERROR: " << buffer->data2[i] << " != " << test2 << std::endl;
    	exit(0);
      }
      int16_t test3 = static_cast<int16_t>(static_cast<double>(test2)/4.0);
      if (buffer->data3[i] != test3){
    	std::cout << "BUFFER 3 ERROR: " << buffer->data3[i] << " != " << test3 << std::endl;
	exit(0);
      }
    }    
    // If buffer is valid, return buffer to pool
    pool.release(buffer);
  }

  std::cout << "Data check SUCCESS" << std::endl;
  
  // Signal completion
  threadDone[threadIndex].store(true);
  
  // Print completion message
  std::cout << "Final buffer emptied.\n";
  
}

